### ISSUE TITLE
Can't join friends when launching the software before launching the game

### ISSUE THREAD

**Issue by Kenshin9977** [shiversoftdev/t7dwidm_patch#1]
I tried with the soft lanched: Can't join a frien though we have both an Open NAT type.
Without the soft: I can join him and he can join me.

**Comment by shiversoftdev** [comment]
> I tried with the soft lanched: Can't join a frien though we have both an Open NAT type.
> Without the soft: I can join him and he can join me.

Please verify if you were friends with each member of the party you were attempting to join. You must be friends on steam and you must have added the player before starting your game.

**Comment by Kenshin9977** [comment]
There was only one player in the lobby I wanted to join and we are friends on Steam for a long time.

**Comment by shiversoftdev** [comment]
I will investigate this when I get the chance. It may be a couple weeks until then, though.

To be perfectly clear as well, unfortunately, it seems as though there are several new methods that the patcher does not handle.
This basically means that the only way to prevent being compromised is to practice safe information security.

My personal routine involves an alt account with all privacy settings enabled on steam, and only playing with close friends or people i trust who are also practicing these security procedures.  You will know you have a correct configuration when you sign into the game with an "Unknown Soldier" playername. 

Unfortunately at this time I don't believe that there is any other effective way to prevent malicious actors from interfering with your game. Activision has no interest in maintaining this title which means from here out I would be having to constantly battle with attackers to try to fix a game which I have no vested interest in. While this tool still will prevent the attacks it was designed to defend against, it will not be effective against new methods, and I cannot guarantee any consistency in protection against these attacks.
